[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']
aptPkgs = ['chromium', 'fonts-liberation', 'libxss1', 'libasound2', 'libatk-bridge2.0-0', 'libdrm2', 'libxcomposite1', 'libxdamage1', 'libxrandr2', 'libgbm1', 'libxkbcommon0', 'libgtk-3-0']

[phases.install]
cmds = [
  'chmod +x railway-install.sh',
  './railway-install.sh'
]

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium' 